"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-23 20:18:14.959604

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_runs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "params",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "metrics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "equity_curve",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "trades",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest_runs")),
    )
    op.create_table(
        "equity_snapshots",
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("equity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("balance", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("open_risk", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.PrimaryKeyConstraint("ts", "mode", name=op.f("pk_equity_snapshots")),
    )
    op.create_table(
        "instruments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("broker", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("market_type", sa.String(length=16), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("tick_size", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("qty_step", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("min_qty", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("max_qty", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("min_notional", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("max_leverage", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("taker_fee", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("maker_fee", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instruments")),
        sa.UniqueConstraint("broker", "symbol", name="uq_instruments_broker_symbol"),
    )
    op.create_table(
        "risk_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_events")),
    )
    op.create_index(op.f("ix_risk_events_type"), "risk_events", ["type"], unique=False)
    op.create_table(
        "secrets",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("ciphertext", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_secrets")),
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column(
            "value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=64), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
    )
    op.create_index("ix_settings_key_id", "settings", ["key", "id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("totp_secret", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("login", name=op.f("uq_users_login")),
    )
    op.create_table(
        "candles",
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("tf", sa.String(length=4), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.Column("turnover", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_candles_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("instrument_id", "tf", "ts", name=op.f("pk_candles")),
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("direction", sa.String(length=8), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("regime", sa.String(length=16), nullable=False),
        sa.Column(
            "components",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("acted", sa.Boolean(), nullable=False),
        sa.Column("reject_reason", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"], ["instruments.id"], name=op.f("fk_signals_instrument_id_instruments")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signals")),
    )
    op.create_index("ix_signals_instrument_ts", "signals", ["instrument_id", "ts"], unique=False)
    op.create_table(
        "trades",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("signal_id", sa.BigInteger(), nullable=True),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("strategy", sa.String(length=32), nullable=False),
        sa.Column("direction", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("qty", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("remaining_qty", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("initial_stop", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("stop_loss", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("tp1", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("tp2", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("tp1_done", sa.Boolean(), nullable=False),
        sa.Column("risk_amount", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("fees", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("r_multiple", sa.Float(), nullable=True),
        sa.Column("exit_price", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("close_reason", sa.String(length=16), nullable=True),
        sa.Column("bars_held", sa.Integer(), nullable=False),
        sa.Column(
            "opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "extra",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"], ["instruments.id"], name=op.f("fk_trades_instrument_id_instruments")
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"], ["signals.id"], name=op.f("fk_trades_signal_id_signals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trades")),
    )
    op.create_index("ix_trades_opened_at", "trades", ["opened_at"], unique=False)
    op.create_index("ix_trades_status", "trades", ["status"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("trade_id", sa.BigInteger(), nullable=False),
        sa.Column("exchange_order_id", sa.String(length=64), nullable=True),
        sa.Column("link_id", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=16), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("order_type", sa.String(length=16), nullable=False),
        sa.Column("price", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("qty", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"], ["trades.id"], name=op.f("fk_orders_trade_id_trades"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("link_id", name=op.f("uq_orders_link_id")),
    )
    op.create_index(op.f("ix_orders_trade_id"), "orders", ["trade_id"], unique=False)
    op.create_table(
        "executions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("exec_id", sa.String(length=64), nullable=True),
        sa.Column("price", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("qty", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("fee", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_executions_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_executions")),
        sa.UniqueConstraint("exec_id", name=op.f("uq_executions_exec_id")),
    )
    op.create_index(op.f("ix_executions_order_id"), "executions", ["order_id"], unique=False)
    # ### end Alembic commands ###

    # TimescaleDB: если расширение доступно (docker-образ timescale/timescaledb),
    # превращаем candles в hypertable. На чистом PostgreSQL таблица остаётся обычной.
    bind = op.get_bind()
    has_timescale = bind.execute(
        sa.text("SELECT 1 FROM pg_available_extensions WHERE name = 'timescaledb'")
    ).scalar()
    if has_timescale:
        op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
        op.execute(
            "SELECT create_hypertable('candles', 'ts', "
            "chunk_time_interval => INTERVAL '30 days', migrate_data => true)"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_executions_order_id"), table_name="executions")
    op.drop_table("executions")
    op.drop_index(op.f("ix_orders_trade_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_trades_status", table_name="trades")
    op.drop_index("ix_trades_opened_at", table_name="trades")
    op.drop_table("trades")
    op.drop_index("ix_signals_instrument_ts", table_name="signals")
    op.drop_table("signals")
    op.drop_table("candles")
    op.drop_table("users")
    op.drop_index("ix_settings_key_id", table_name="settings")
    op.drop_table("settings")
    op.drop_table("secrets")
    op.drop_index(op.f("ix_risk_events_type"), table_name="risk_events")
    op.drop_table("risk_events")
    op.drop_table("instruments")
    op.drop_table("equity_snapshots")
    op.drop_table("backtest_runs")
    # ### end Alembic commands ###
